[package]
name = "common"
version = "0.2.0"
edition.workspace = true
authors.workspace = true

[dependencies]
actix-session.workspace = true
actix-web.workspace = true
fxhash.workspace = true
minify-html.workspace = true
regex.workspace = true
serde.workspace = true
tera.workspace = true
validator.workspace = true
