x-rust-base: &rust-base
    build:
        context: .
        dockerfile: app/Dockerfile.dev
    volumes:
        - ./Cargo.toml:/app/Cargo.toml:ro
        - ./Cargo.lock:/app/Cargo.lock
        - ./app:/app/app
        - ./lib:/app/lib
        - target:/app/target
        - cargo-cache:/usr/local/cargo/registry
    networks:
        - untroche

services:
    # --- Nginx (リバースプロキシ) ---
    nginx:
        image: nginx:alpine
        ports:
            - "8080:8080"
        environment:
            - ASSET_SUFFIX=-min
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
        volumes:
            - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
            - ./app/common/resource:/app/app/common
            - ./app/portal/resource:/app/app/portal
            - ./app/erltod/resource:/app/app/erltod
            - ./app/ondyst/resource:/app/app/ondyst
        depends_on:
            - portal
            # - erltod
            - ondyst
        networks:
            - untroche

    watcher:
        build:
            context: .
            dockerfile: watcher/Dockerfile.dev
        environment:
            - MINIFY=true
        volumes:
            - ./app:/app/app
            - ./watcher/tsconfig.json:/app/tsconfig.json:ro
            - ./watcher/compile.sh:/app/compile.sh:ro
            - ./watcher/compile_all.sh:/app/compile_all.sh:ro

    portal:
        <<: *rust-base
        environment:
            - APP_NAME=portal
            - SERVER_PORT=8000
            - DATABASE_URL=sqlite:app/portal/database.db
            - RUST_LOG=debug
        networks:
            - untroche

    # erltod:
    #     <<: *rust-base
    #     environment:
    #         - APP_NAME=erltod
    #         - SERVER_PORT=8005
    #         - DATABASE_URL=sqlite:app/erltod/database.db
    #     networks:
    #         - untroche

    ondyst:
        <<: *rust-base
        environment:
            - APP_NAME=ondyst
            - SERVER_PORT=8006
            - DATABASE_URL=sqlite:app/ondyst/database.db
        networks:
            - untroche

networks:
    untroche:

volumes:
    target:
    cargo-cache:
