FROM node:alpine
RUN npm install -g chokidar-cli esbuild
ENV SHELL=/bin/sh

WORKDIR /app

CMD ["chokidar", "app/*/resource/ts/**/*.ts", "app/*/resource/style/**/*.css", "-c", "sh compile.sh {path}", "--initial", "--polling"]
