FROM node:alpine
RUN npm install -g chokidar-cli esbuild
ENV SHELL=/bin/sh

WORKDIR /app

CMD ["sh","-c", "if [ \"$MINIFY\" = \"true\" ]; then chokidar 'app/*/resource/ts/**/*.ts' 'app/*/resource/style/**/*.css' -c 'sh compile.sh \"{path}\" true' --initial --polling; else chokidar 'app/*/resource/ts/**/*.ts' -c 'sh compile.sh \"{path}\" false' --initial --polling; fi"]
