FROM rust:slim-bookworm
ENV SERVER_HOST=0.0.0.0
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install watchexec-cli
WORKDIR /app/app

CMD ["sh", "-c", "cd ${APP_NAME} && exec watchexec --print-events --restart --poll -w src -w resource -w Cargo.toml -e rs,html,toml -i resource/*/**/*.html -- cargo run --bin ${APP_NAME}"]
