FROM rust:slim-bookworm
ENV SERVER_HOST=0.0.0.0
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install watchexec-cli
WORKDIR /app

CMD ["sh", "-c", "exec watchexec --restart --poll -w app/${APP_NAME} -w Cargo.toml -e rs,html,toml -- cargo run --bin ${APP_NAME}"]
