events {
	worker_connections 1024;
}

http {
	include response;
	include domain_map;

	# 未定義ホストヘッダーへのアクセスを弾く
	server {
		listen 80 default_server;
		server_name _;

		return 404;
	}

	# メイン
	server {
		listen 80;
		server_name
			untroche.com
			*.untroche.com
			localhost
			*.localhost;

		root /app/app/$app_name;
		set $upstream http://$app_name:$app_port; # 開発用

		resolver 127.0.0.11 valid=30s; # 開発用

		location ~ ^/(?<dir>script|style)/(?<file>.+)$ {
			try_files /$dir/$file /common/$dir/$file;
			include log_off;
		}
		location /common/ {
			alias /app/app/common/;
			include log_off;
		}
		location /image/ {
			include log_off;
		}
		location /.well-known/ {
			alias /app/app/common/.well-known/;
			include log_off;
		}
		location = /favicon.ico {
			try_files /image/favicon.ico =404;
			include log_off;
		}

		location ~ /stream$ {
			proxy_pass $upstream;
			include proxy_params;

			proxy_set_header Connection "";
			proxy_buffering off;
			proxy_cache off;
			proxy_read_timeout 86400s;

			gzip off;
		}

		location / {
			proxy_pass $upstream;
			include proxy_params;
		}
	}
}
