events {
	worker_connections 1024;
}

http {
	include response;
	include domain_map;

	# 証明書設定
	ssl_certificate /app/ssl/fullchain.pem;
	ssl_certificate_key /app/ssl/privkey.pem;

	# 未定義ホストヘッダーへのアクセスを弾く
	server {
		listen 80 default_server;
		listen 443 ssl default_server;
		server_name _;

		return 404;
	}

	# HTTPリダイレクト
	server {
		listen 80;
		server_name untroche.com *.untroche.com localhost *.localhost;
		access_log off;
		return 301 https://$host$request_uri;
	}

	# メイン
	server {
		listen 443 ssl;
		server_name
			untroche.com
			*.untroche.com
			localhost
			*.localhost;

		# プロトコルと暗号設定
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;
		add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

		root /app/app/$app_name;
		set $upstream http://127.0.0.1:$app_port; # 本番用

		location ~ ^/common/(?<dir>script|style)/(?<file>.+)$ {
			alias /app/app/common/$dir-min/$file;
			include log_off;
		}
		location ~ ^/(?<dir>script|style)/(?<file>.+)$ {
			try_files /$dir-min/$file /common/$dir-min/$file;
			include log_off;
		}
		location /common/ {
			alias /app/app/common/;
			include log_off;
		}
		location /image/ {
			include log_off;
		}
		location /.well-known/ {
			alias /app/app/common/.well-known/;
			include log_off;
		}
		location = /favicon.ico {
			try_files /image/favicon.ico =404;
			include log_off;
		}

		location ~ /stream$ {
			proxy_pass $upstream;
			include proxy_params;

			proxy_set_header Connection "";
			proxy_buffering off;
			proxy_cache off;
			proxy_read_timeout 86400s;

			gzip off;
		}

		location / {
			proxy_pass $upstream;
			include proxy_params;
		}
	}
}
